export const GET_TRACK_LIST = 'GET_TRACK_LIST';
export const TOGGLE_PLAY = 'TOGGLE_PLAY';
export const CURRENT_TRACK = 'CURRENT_TRACK';
export const SET_CURRENT_PLAY_NODE = 'SET_CURRENT_PLAY_NODE';

export const SET_CURRENT_PLAYER_EXAMPLE = 'SET_CURRENT_PLAYER_EXAMPLE';
export const SET_CURRENT_TRACK_BUFFER = 'SET_CURRENT_TRACK_BUFFER';