name: Dev deploy
on:
  push:
    branches:
      - dev
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
#       - uses: actions/checkout@master
#       - name: Kaniko build
#         uses: outillage/kaniko-action@master
#         with:
#           image: ultradesu/hexound_dev
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd hexound_dev/
            git pull
            echo REACT_APP_BASE_URL=https://dev-hexound.hexor.ru/api/ > web/.env
            docker-compose build api-dev web-dev
            docker-compose up -d api-dev web-dev
