name: Prod deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    env:
        REACT_APP_BASE_URL: https://hexound.hexor.ru/api/
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd hexound_prod/
            git pull
            echo ###########################
            echo ${{ REACT_APP_BASE_URL }}
            echo ###########################
            docker-compose build api-prod web-prod
            docker-compose up -d api-prod web-prod